export default async function get_lirik(text) {
    const itunesRes = await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(text)}&entity=song&limit=1`);
    const itunesData = await itunesRes.json();
    console.log('mendapatkan lagu')
    if (itunesData.resultCount > 0) {
        const lagu = itunesData.results[0];
        const artis = lagu.artistName;
        const judul = lagu.trackName;
        const lrcRes = await fetch(`https://lrclib.net/api/get?artist_name=${encodeURIComponent(artis)}&track_name=${encodeURIComponent(judul)}`);
        const lrcData = await lrcRes.json();
        console.log({
            judul: judul,
            artis: artis,
            lirik: lrcData.plainLyrics || "Lirik tidak ditemukan untuk lagu ini."
        })
        const format =
            `╔══════════════════╗\n` +
            `🎵  *INFORMASI MUSIK* 🎵\n` +
            `╚══════════════════╝\n\n` +
            `📝 *Judul:* ${judul}\n` +
            `👤 *Artis:* ${artis}\n\n` +
            `──────────────────\n` +
            `📑 *LIRIK LAGU*\n` +
            `──────────────────\n\n` +
            `${lrcData.plainLyrics || "_Lirik tidak ditemukan untuk lagu ini._"}\n\n` +
            `──────────────────\n` +
            `©️ _Generated by MusicBot_`;

        return format;
    } else {
        console.log('tidak menemukan lagu')
        return null;
    }
}